DOCKER-129 Improve the process of locally built image
brianchandotcom/liferay-docker pull request #281
Opened 2022-06-29 13:15 UTC by Akos-Kreutz

For example:

]$ ./build_local_image.sh ~/bundles/ dxp snapshot no_warm_up no_test_image

Builds the image in less than 30 seconds

2022-07-26 15:08 UTC, gamerson requested changes

2022-07-26 15:08 UTC, gamerson commented on _common.sh
> +	sed -i'' 's/${TARGETARCH}'/$(get_current_arch)/ "${TEMP_DIR}"/Dockerfile
```suggestion
	sed -i'.bak' 's/${TARGETARCH}'/$(get_current_arch)/ "${TEMP_DIR}"/Dockerfile
```

2022-07-26 15:08 UTC, gamerson commented on _common.sh
> +	sed -i'' 's/${TARGETARCH}'/$(get_current_arch)/ "${TEMP_DIR}"/Dockerfile
For MacOS, you must provide a backup extension when `sed` is doing inline editing.  The `-i'.bak'` is compatible with GNU/linux and BSD/MacOS.

2022-07-26 16:38 UTC, gamerson commented on _common.sh
> +	sed -i'' 's/--platform=${TARGETPLATFORM} //g' "${TEMP_DIR}"/Dockerfile
```suggestion
	sed -i'.bak' 's/--platform=${TARGETPLATFORM} //g' "${TEMP_DIR}"/Dockerfile
```
There is another one :)

2022-08-01 14:05 UTC, closed without merging

2022-08-01 14:06 UTC, brianchandotcom commented
@gamerson @Akos-Kreutz @rotty3000 this is in!

2022-08-01 14:18 UTC, gamerson commented
thanks @brianchandotcom  and @Akos-Kreutz   this helps a lot.

2022-08-03 15:23 UTC, rotty3000 commented
:tada: